spring.application.name=Lizma

#Data
spring.datasource.url=jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update


#JWT
token.signing.key = ${SECRET_KEY}

#App
app.externalBaseUrl=http://localhost:8080
app.invites.pathPrefix=/i
app.invites.ttlHours=168

# ==== Spotify (PKCE) ====
spotify.clientId=886cea2ad68346a597acede21adaf379
spotify.redirectUri=lizma://oauth-callback/spotify

# ==== Apple Music ====
apple.devToken=FUTURE_APPLE_MUSIC_TOKEN